FROM public.ecr.aws/lambda/python:3.11

WORKDIR /var/task

COPY app ./app
# COPY chroma_db ./chroma_db
COPY chroma_db /tmp/chroma_db

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["app.main.handler"]
